name: Build SunamoFluentFtp

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoFluentFtp
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoFluentFtp/SunamoFluentFtp.csproj

    - name: Build
      run: dotnet build SunamoFluentFtp/SunamoFluentFtp.csproj --configuration Release --no-restore

  test:
    name: Test SunamoFluentFtp.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoFluentFtp.Tests/SunamoFluentFtp.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoFluentFtp.Tests/SunamoFluentFtp.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoFluentFtp.Tests/SunamoFluentFtp.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
